# For documentation, see https://golangci-lint.run/usage/configuration/

run:
  build-tags:
    - seccomp

linters:
  enable:
    - errorlint
    - nolintlint
    - gofumpt
    - unconvert
    - unparam

linters-settings:
  govet:
    enable:
      - nilness
