# This is deliberately a separate workflow -- so that it still runs when
# another workflow file is broken.
name: actionlint
on:
  push:
    tags:
      - v*
    branches:
      - main
      - release-*
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: devops-actions/actionlint@ec02b36684b2f574f1d219ad0a43b082e46bf3e4 # v0.1.13

  all-done:
    needs:
    - actionlint
    runs-on: ubuntu-24.04
    steps:
    - run: echo "All jobs completed"
