# This is deliberately a separate workflow -- so that it still runs when
# another workflow file is broken.
name: actionlint
on:
  push:
    tags:
      - v*
    branches:
      - main
      - release-*
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: kjanat/actionlint@c9565647ad2ff016b50b148a595dfcce50975816 # v1.13.0

  all-done:
    needs:
    - actionlint
    runs-on: ubuntu-24.04
    steps:
    - run: echo "All jobs completed"
